name: kolumpio
favicon: null
layout_spectrum: 0.8634548811241984
typography_spectrum: 0.89622
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#692845'
    - '#fefefd'
    - '#bda2ae'
    - '#976d80'
    - '#d7c7cd'
  brandStrength: 0.26944385562092066
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 1
purpose: []
